# Generated by Django 4.0.6 on 2024-03-15 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CyberDefender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='browser',
            field=models.CharField(max_length=100, verbose_name='browser'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='browser_version_string',
            field=models.CharField(max_length=100, verbose_name='browser_version'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='cookies',
            field=models.TextField(max_length=256, verbose_name='cookies'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='country',
            field=models.CharField(max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='device',
            field=models.CharField(max_length=100, verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='ip_address',
            field=models.CharField(max_length=100, verbose_name='ip_address'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='network',
            field=models.CharField(max_length=100, verbose_name='network'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='postal_code'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='user_agent',
            field=models.TextField(max_length=256, verbose_name='user_agent'),
        ),
    ]
