# Generated by Django 4.0.6 on 2024-03-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyberDefender', '0002_alter_uservisit_browser_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uservisit',
            table='cyberdefender_uservisit',
        ),
    ]
