# Generated by Django 3.0.14 on 2024-03-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberDefender', '0004_alter_uservisit_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
